/**
 * @file orxExtensions.h
 * !! This file is automatically generated by init, do not modify manually. !!
 * @date 18-Jan-2025
 */

#ifndef _orxEXTENSIONS_H_
#define _orxEXTENSIONS_H_

#define orxMOVIE_IMPL
#include "orxMovie.h"
#undef orxMOVIE_IMPL

#define orxMOD_IMPL
#include "orxMod.h"
#undef orxMOD_IMPL

#define orxNOISETEXTURE_IMPL
#include "orxNoiseTexture.h"
#undef orxNOISETEXTURE_IMPL

#define orxBUNDLE_IMPL
#include "orxBundle.h"
#undef orxBUNDLE_IMPL

void InitExtensions()
{
  // Initialize movie support
  orxMovie_Init();

  // Initialize MOD support
  orxMod_Init();

  // Initialize noise texture support
  orxNoiseTexture_Init();

}

void ExitExtensions()
{
  // Exit from MOD support
  orxMod_Exit();

  // Exit from movie support
  orxMovie_Exit();

  // Exit from noise texture support
  orxNoiseTexture_Exit();

  // Exit from bundle support
  orxBundle_Exit();

}

void BootstrapExtensions()
{
  // Initialize bundle resource type
  orxBundle_Init();

  // Add config storage to find the initial config file
  orxResource_AddStorage(orxCONFIG_KZ_RESOURCE_GROUP, orxBUNDLE_KZ_RESOURCE_STORAGE, orxFALSE);
  orxResource_AddStorage(orxCONFIG_KZ_RESOURCE_GROUP, orxBUNDLE_KZ_RESOURCE_STORAGE "AdventureTycoon.obr", orxFALSE);
  orxResource_AddStorage(orxCONFIG_KZ_RESOURCE_GROUP, "../data/config", orxFALSE);
}

#endif // _orxEXTENSIONS_H_
